name: Test GraalJS Gradle Webpack Guide
on:
  push:
    paths:
      - '**'
  pull_request:
    paths:
      - '**'
  workflow_dispatch:

permissions:
  contents: read
jobs:
  run:
    name: 'graaljs-gradle-webpack-guide'
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21.0.6'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cache: 'gradle'
      - name: Build and run 'graaljs-gradle-webpack-guide'
        run: |
          ./gradlew build
          ./gradlew run --args="https://www.graalvm.org/javascript"
